// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xyivxhkmirleuhpkbwcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5aXZ4aGttaXJsZXVocGtid2N3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMjA5NTYsImV4cCI6MjA1OTc5Njk1Nn0.BrIeVBJX4G-powlYAX9ZM1X6HlvxC4kxM04gXtVtmtQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);